server:
  port: 6601

spring:
  application:
    name: MicroService-Nacos-Consumer                          # 对外暴漏的微服务名称，十分重要


#################################################### Nacos Server 地址 ##################################################
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848


service-url:
  nacos-user-service: http://MicroService-Nacos-Provider
