server:
  port: 1111

spring:
  application:
    name: MicroService-Nacos-Seata-Order-1111                   # 对外暴漏的微服务名称，十分重要

  ########################################### JDBC 配置 ###########################################
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver                 # 数据库驱动
    url: jdbc:mysql://49.232.161.139:3306/seata                 # 数据库url
    username: root                                              # 数据库登陆用户名
    password: 1207                                              # 数据库登陆密码
    hikari:
      minimum-idle: 5                                           # 最小空闲连接数量
      idle-timeout: 0                                           # 空闲连接存活最大时间，默认600000（10分钟）
      maximum-pool-size: 10                                     # 连接池最大连接数，默认是10
      auto-commit: true                                         # 此属性控制从池返回的连接的默认自动提交行为，默认值：true
      pool-name: YoungHikariConnectionPool                      # 连接池名称
      max-lifetime: 0                                           # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      connection-timeout: 0                                     # 数据库连接超时时间,默认30秒，即30000
      connection-test-query: SELECT 1                           # 数据库连接测试

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace:
        username: "nacos"
        password: "nacos"
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
        port: 8719

seata:
  application-id: ${spring.application.name}
  tx-service-group: Service-Order-Group

  service:
    grouplist:
      seata-server: 127.0.0.1:8091

  registry:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848

  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848

########################################### MyBatis 配置 ###########################################
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml              # 指定 mapper.xml 的位置
  type-aliases-package: com.young.entity                        # 扫描实体类的位置,在此处指明扫描实体类的包，在 mapper.xml 中就可以不写实体类的全路径名
  configuration:
    map-underscore-to-camel-case: true                          # 默认开启驼峰命名法，可以不用设置该属性
