server:
  port: 9903

########################################### Spring cloud 自定义服务名称和 ip 地址 ###############################################
eureka:
  client:
    register-with-eureka: false         # 本微服务为服务消费者，不需要将自己注册到服务注册中心
    fetch-registry: true                # 本微服务为服务消费者，需要到服务注册中心搜索服务
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/ #服务注册中心集群


feign:
  circuitbreaker:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 7000

    DeptHystrixService#deptTimeout(Integer):
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
