server:
  port: 8803

spring:
  application:
    name: MicroService-Eureka-Provider                          # 对外暴漏的微服务名称，十分重要

########################################### JDBC 配置 ###########################################
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver                 # 数据库驱动
    url: jdbc:mysql://49.232.161.139:3306/spring_cloud_db3      # 数据库url
    username: root                                              # 数据库登陆用户名
    password: 1207                                              # 数据库登陆密码

########################################### MyBatis 配置 ###########################################
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml              # 指定 mapper.xml 的位置
  type-aliases-package: com.young.entity                        # 扫描实体类的位置,在此处指明扫描实体类的包，在 mapper.xml 中就可以不写实体类的全路径名
  configuration:
    map-underscore-to-camel-case: true                          # 默认开启驼峰命名法，可以不用设置该属性

########################################### Spring cloud 自定义服务名称和 ip 地址 ###############################################
eureka:
  client:                                                       # 将客户端注册到 eureka 服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka, http://eureka7003.com:7003/eureka   # Eureka 集群注册中心在 application.yml 中暴露出来的注册地址

  instance:
    instance-id: MicroService-Provider-8002                     # 自定义服务名称信息
    prefer-ip-address: true                                     # 显示访问路径的 ip 地址